CREATE USER YourUser IDENTIFIED BY YourPassword;
GRANT CREATE SESSION TO YourUser;

CREATE OR REPLACE DIRECTORY PORTAL_FILES_IN_OUT_DIR AS 'YourPathToTheDirectory';
GRANT READ,WRITE ON DIRECTORY PORTAL_FILES_IN_OUT_DIR TO YourUser;
